version: "1.0"
info:
  model: int-scaffold
packages:
- name: EdgeIC_Automaion1007
  gitServerName: ICAccountTest1007
  gitUrl: https://github.com/MeghaRaj69/EdgeIC_Automaion1007
  gitUsername: MeghaRaj69
  gitToken: edge.scaffolding.EdgeIC_Automaion1007.ICAccountTest1007.gitToken
  gitBranch: Test/CustomBranch/Test
